spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myfile
    username: root
    password: dj123456

mybatis-plus:
  mapper-locations: classpath:com.dj.myfile/**/*.xml  #找xml文件用的
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #sql打印日志